import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"
import modelProviders from "./docs/providers/index.json"

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		"index",
		{
			type: "category",
			label: "Roo Code VSCode Extension",
			items: [
				"getting-started/installing",
				"getting-started/connecting-api-provider",
				"getting-started/your-first-task",
				"basic-usage/the-chat-interface",
				"basic-usage/typing-your-requests",
				"basic-usage/how-tools-work",
				"basic-usage/context-mentions",
				"basic-usage/using-modes",
				"tips-and-tricks",
				"reporting-errors",
				{
					label: "Features",
					type: "category",
					items: [
						"features/api-configuration-profiles",
						"features/auto-approving-actions",
						"features/boomerang-tasks",
						"features/checkpoints",
						"features/code-actions",
						"features/codebase-indexing",
						"features/custom-instructions",
						"features/diagnostics-integration",
						"features/custom-modes",
						"features/enhance-prompt",
						"features/settings-management",
						"features/intelligent-context-condensing",
						"features/keyboard-shortcuts",
						"features/marketplace",
						"features/message-queueing",
						"features/model-temperature",
						"features/concurrent-file-reads",
						"features/rooignore",
						"features/skills",
						"features/slash-commands",
						"features/suggested-responses",
						"features/task-todo-list",
						"features/worktrees",
						"features/shell-integration",
						"features/more-features",
					],
				},
				{
					type: "category",
					label: "MCP",
					items: [
						{
							type: "doc",
							id: "features/mcp/overview",
							label: "MCP Overview",
						},
						"features/mcp/using-mcp-in-roo",
						"features/mcp/what-is-mcp",
						"features/mcp/server-transports",
						"features/mcp/mcp-vs-api",
						"features/mcp/recommended-mcp-servers",
					],
				},
				{
					type: "category",
					label: "Experimental",
					items: [
						"features/experimental/experimental-features",
						"features/experimental/custom-tools",
						"features/experimental/concurrent-file-edits",
						"features/experimental/background-editing",
						"features/image-generation",
						"advanced-usage/available-tools/run-slash-command",
					],
				},
				{
					type: "category",
					label: "Advanced Usage",
					items: [
						{
							type: "category",
							label: "Available Tools",
							items: [
								"advanced-usage/available-tools/tool-use-overview",
								"advanced-usage/available-tools/access-mcp-resource",
								"advanced-usage/available-tools/apply-diff",
								"advanced-usage/available-tools/apply-patch",
								"advanced-usage/available-tools/ask-followup-question",
								"advanced-usage/available-tools/attempt-completion",
								"advanced-usage/available-tools/codebase-search",
								"advanced-usage/available-tools/edit",
								"advanced-usage/available-tools/edit-file",
								"advanced-usage/available-tools/execute-command",
								"advanced-usage/available-tools/generate-image",
								"advanced-usage/available-tools/list-files",
								"advanced-usage/available-tools/new-task",
								"advanced-usage/available-tools/read-command-output",
								"advanced-usage/available-tools/read-file",
								"advanced-usage/available-tools/run-slash-command",
								"advanced-usage/available-tools/search-files",
								"advanced-usage/available-tools/search-replace",
								"advanced-usage/available-tools/skill",
								"advanced-usage/available-tools/switch-mode",
								"advanced-usage/available-tools/update-todo-list",
								"advanced-usage/available-tools/use-mcp-tool",
								"advanced-usage/available-tools/write-to-file",
							],
						},
						"advanced-usage/context-poisoning",
						"advanced-usage/large-projects",
						"advanced-usage/local-models",
						"advanced-usage/prompt-engineering",
						"advanced-usage/prompt-structure",
						"advanced-usage/rate-limits-costs",
						"advanced-usage/roo-code-nightly",
					],
				},
			],
		},
		{
			type: "category",
			label: "Model Providers",
			items: [
				{
					type: "doc",
					id: "providers/index",
					label: "About Model Providers",
				},
				...modelProviders.providers.map((provider) => ({
					type: "doc" as const,
					id: provider.id,
					label: provider.title,
				})),
			],
		},
		{
			type: "category",
			label: "Extension Release Notes",
			items: [
				"update-notes/index",
				{
					type: "category",
					label: "3.50",
					items: [{ type: "doc", id: "update-notes/v3.50.0", label: "3.50.0" }],
				},
				{
					type: "category",
					label: "3.49",
					items: [{ type: "doc", id: "update-notes/v3.49.0", label: "3.49.0" }],
				},
				{
					type: "category",
					label: "3.48",
					items: [
						{ type: "doc", id: "update-notes/v3.48.1", label: "3.48.1" },
						{ type: "doc", id: "update-notes/v3.48.0", label: "3.48.0" },
					],
				},
				{
					type: "category",
					label: "3.47",
					items: [{ type: "doc", id: "update-notes/v3.47.0", label: "3.47.0" }],
				},
				{
					type: "category",
					label: "3.46",
					items: [
						{ type: "doc", id: "update-notes/v3.46", label: "3.46 Combined" },
						{ type: "doc", id: "update-notes/v3.46.2", label: "3.46.2" },
						{ type: "doc", id: "update-notes/v3.46.1", label: "3.46.1" },
						{ type: "doc", id: "update-notes/v3.46.0", label: "3.46.0" },
					],
				},
				{
					type: "category",
					label: "3.45",
					items: [{ type: "doc", id: "update-notes/v3.45.0", label: "3.45.0" }],
				},
				{
					type: "category",
					label: "3.44",
					items: [
						{ type: "doc", id: "update-notes/v3.44", label: "3.44 Combined" },
						{ type: "doc", id: "update-notes/v3.44.2", label: "3.44.2" },
						{ type: "doc", id: "update-notes/v3.44.1", label: "3.44.1" },
						{ type: "doc", id: "update-notes/v3.44.0", label: "3.44.0" },
					],
				},
				{
					type: "category",
					label: "3.43",
					items: [{ type: "doc", id: "update-notes/v3.43.0", label: "3.43.0" }],
				},
				{
					type: "category",
					label: "3.42",
					items: [{ type: "doc", id: "update-notes/v3.42.0", label: "3.42.0" }],
				},
				{
					type: "category",
					label: "3.41",
					items: [
						{ type: "doc", id: "update-notes/v3.41.2", label: "3.41.2" },
						{ type: "doc", id: "update-notes/v3.41.1", label: "3.41.1" },
						{ type: "doc", id: "update-notes/v3.41.0", label: "3.41.0" },
					],
				},
				{
					type: "category",
					label: "3.40",
					items: [
						{ type: "doc", id: "update-notes/v3.40", label: "3.40 Combined" },
						{ type: "doc", id: "update-notes/v3.40.1", label: "3.40.1" },
						{ type: "doc", id: "update-notes/v3.40.0", label: "3.40.0" },
					],
				},
				{
					type: "category",
					label: "3.39",
					items: [
						{ type: "doc", id: "update-notes/v3.39", label: "3.39 Combined" },
						{ type: "doc", id: "update-notes/v3.39.3", label: "3.39.3" },
						{ type: "doc", id: "update-notes/v3.39.2", label: "3.39.2" },
						{ type: "doc", id: "update-notes/v3.39.1", label: "3.39.1" },
						{ type: "doc", id: "update-notes/v3.39.0", label: "3.39.0" },
					],
				},
				{
					type: "category",
					label: "3.38",
					items: [
						{ type: "doc", id: "update-notes/v3.38", label: "3.38 Combined" },
						{ type: "doc", id: "update-notes/v3.38.3", label: "3.38.3" },
						{ type: "doc", id: "update-notes/v3.38.2", label: "3.38.2" },
						{ type: "doc", id: "update-notes/v3.38.1", label: "3.38.1" },
						{ type: "doc", id: "update-notes/v3.38.0", label: "3.38.0" },
					],
				},
				{
					type: "category",
					label: "3.37",
					items: [
						{ type: "doc", id: "update-notes/v3.37", label: "3.37 Combined" },
						{ type: "doc", id: "update-notes/v3.37.0", label: "3.37.0" },
						{ type: "doc", id: "update-notes/v3.37.1", label: "3.37.1" },
					],
				},
				{
					type: "category",
					label: "3.36",
					items: [
						{ type: "doc", id: "update-notes/v3.36", label: "3.36 Combined" },
						{ type: "doc", id: "update-notes/v3.36.16", label: "3.36.16" },
						{ type: "doc", id: "update-notes/v3.36.15", label: "3.36.15" },
						{ type: "doc", id: "update-notes/v3.36.14", label: "3.36.14" },
						{ type: "doc", id: "update-notes/v3.36.13", label: "3.36.13" },
						{ type: "doc", id: "update-notes/v3.36.12", label: "3.36.12" },
						{ type: "doc", id: "update-notes/v3.36.11", label: "3.36.11" },
						{ type: "doc", id: "update-notes/v3.36.10", label: "3.36.10" },
						{ type: "doc", id: "update-notes/v3.36.9", label: "3.36.9" },
						{ type: "doc", id: "update-notes/v3.36.7", label: "3.36.7" },
						{ type: "doc", id: "update-notes/v3.36.6", label: "3.36.6" },
						{ type: "doc", id: "update-notes/v3.36.5", label: "3.36.5" },
						{ type: "doc", id: "update-notes/v3.36.4", label: "3.36.4" },
						{ type: "doc", id: "update-notes/v3.36.3", label: "3.36.3" },
						{ type: "doc", id: "update-notes/v3.36.2", label: "3.36.2" },
						{ type: "doc", id: "update-notes/v3.36.1", label: "3.36.1" },
						{ type: "doc", id: "update-notes/v3.36.0", label: "3.36.0" },
					],
				},
				{
					type: "category",
					label: "3.35",
					items: [
						{ type: "doc", id: "update-notes/v3.35", label: "3.35 Combined" },
						{ type: "doc", id: "update-notes/v3.35.5", label: "3.35.5" },
						{ type: "doc", id: "update-notes/v3.35.4", label: "3.35.4" },
						{ type: "doc", id: "update-notes/v3.35.3", label: "3.35.3" },
						{ type: "doc", id: "update-notes/v3.35.2", label: "3.35.2" },
						{ type: "doc", id: "update-notes/v3.35.1", label: "3.35.1" },
						{ type: "doc", id: "update-notes/v3.35.0", label: "3.35.0" },
					],
				},
				{
					type: "category",
					label: "3.34",
					items: [
						{ type: "doc", id: "update-notes/v3.34", label: "3.34 Combined" },
						{ type: "doc", id: "update-notes/v3.34.8", label: "3.34.8" },
						{ type: "doc", id: "update-notes/v3.34.7", label: "3.34.7" },
						{ type: "doc", id: "update-notes/v3.34.6", label: "3.34.6" },
						{ type: "doc", id: "update-notes/v3.34.5", label: "3.34.5" },
						{ type: "doc", id: "update-notes/v3.34.4", label: "3.34.4" },
						{ type: "doc", id: "update-notes/v3.34.3", label: "3.34.3" },
						{ type: "doc", id: "update-notes/v3.34.2", label: "3.34.2" },
						{ type: "doc", id: "update-notes/v3.34.1", label: "3.34.1" },
						{ type: "doc", id: "update-notes/v3.34.0", label: "3.34.0" },
					],
				},
				{
					type: "category",
					label: "3.33",
					items: [
						{ type: "doc", id: "update-notes/v3.33", label: "3.33 Combined" },
						{ type: "doc", id: "update-notes/v3.33.3", label: "3.33.3" },
						{ type: "doc", id: "update-notes/v3.33.2", label: "3.33.2" },
						{ type: "doc", id: "update-notes/v3.33.1", label: "3.33.1" },
						{ type: "doc", id: "update-notes/v3.33.0", label: "3.33.0" },
					],
				},
				{
					type: "category",
					label: "3.32",
					items: [
						{ type: "doc", id: "update-notes/v3.32", label: "3.32 Combined" },
						{ type: "doc", id: "update-notes/v3.32.1", label: "3.32.1" },
						{ type: "doc", id: "update-notes/v3.32.0", label: "3.32.0" },
					],
				},
				{
					type: "category",
					label: "3.31",
					items: [
						{ type: "doc", id: "update-notes/v3.31", label: "3.31 Combined" },
						{ type: "doc", id: "update-notes/v3.31.3", label: "3.31.3" },
						{ type: "doc", id: "update-notes/v3.31.2", label: "3.31.2" },
						{ type: "doc", id: "update-notes/v3.31.1", label: "3.31.1" },
						{ type: "doc", id: "update-notes/v3.31.0", label: "3.31.0" },
					],
				},
				{
					type: "category",
					label: "3.30",
					items: [
						{ type: "doc", id: "update-notes/v3.30", label: "3.30 Combined" },
						{ type: "doc", id: "update-notes/v3.30.3", label: "3.30.3" },
						{ type: "doc", id: "update-notes/v3.30.2", label: "3.30.2" },
						{ type: "doc", id: "update-notes/v3.30.1", label: "3.30.1" },
						{ type: "doc", id: "update-notes/v3.30.0", label: "3.30.0" },
					],
				},
				{
					type: "category",
					label: "3.29",
					items: [
						{ type: "doc", id: "update-notes/v3.29", label: "3.29 Combined" },
						{ type: "doc", id: "update-notes/v3.29.5", label: "3.29.5" },
						{ type: "doc", id: "update-notes/v3.29.4", label: "3.29.4" },
						{ type: "doc", id: "update-notes/v3.29.3", label: "3.29.3" },
						{ type: "doc", id: "update-notes/v3.29.2", label: "3.29.2" },
						{ type: "doc", id: "update-notes/v3.29.1", label: "3.29.1" },
						{ type: "doc", id: "update-notes/v3.29.0", label: "3.29.0" },
					],
				},
				{
					type: "category",
					label: "3.28",
					items: [
						{ type: "doc", id: "update-notes/v3.28", label: "3.28 Combined" },
						{ type: "doc", id: "update-notes/v3.28.8", label: "3.28.8" },
						{ type: "doc", id: "update-notes/v3.28.7", label: "3.28.7" },
						{ type: "doc", id: "update-notes/v3.28.6", label: "3.28.6" },
						{ type: "doc", id: "update-notes/v3.28.5", label: "3.28.5" },
						{ type: "doc", id: "update-notes/v3.28.4", label: "3.28.4" },
						{ type: "doc", id: "update-notes/v3.28.3", label: "3.28.3" },
						{ type: "doc", id: "update-notes/v3.28.2", label: "3.28.2" },
						{ type: "doc", id: "update-notes/v3.28.1", label: "3.28.1" },
						{ type: "doc", id: "update-notes/v3.28.0", label: "3.28.0" },
					],
				},
				{
					type: "category",
					label: "3.27",
					items: [{ type: "doc", id: "update-notes/v3.27.0", label: "3.27.0" }],
				},
				{
					type: "category",
					label: "3.26",
					items: [
						{ type: "doc", id: "update-notes/v3.26", label: "3.26 Combined" },
						{ type: "doc", id: "update-notes/v3.26.7", label: "3.26.7" },
						{ type: "doc", id: "update-notes/v3.26.6", label: "3.26.6" },
						{ type: "doc", id: "update-notes/v3.26.5", label: "3.26.5" },
						{ type: "doc", id: "update-notes/v3.26.4", label: "3.26.4" },
						{ type: "doc", id: "update-notes/v3.26.3", label: "3.26.3" },
						{ type: "doc", id: "update-notes/v3.26.2", label: "3.26.2" },
						{ type: "doc", id: "update-notes/v3.26.1", label: "3.26.1" },
						{ type: "doc", id: "update-notes/v3.26.0", label: "3.26.0" },
					],
				},
				{
					type: "category",
					label: "3.25",
					items: [
						{ type: "doc", id: "update-notes/v3.25", label: "3.25 Combined" },
						{ type: "doc", id: "update-notes/v3.25.23", label: "3.25.23" },
						{ type: "doc", id: "update-notes/v3.25.22", label: "3.25.22" },
						{ type: "doc", id: "update-notes/v3.25.21", label: "3.25.21" },
						{ type: "doc", id: "update-notes/v3.25.20", label: "3.25.20" },
						{ type: "doc", id: "update-notes/v3.25.19", label: "3.25.19" },
						{ type: "doc", id: "update-notes/v3.25.18", label: "3.25.18" },
						{ type: "doc", id: "update-notes/v3.25.17", label: "3.25.17" },
						{ type: "doc", id: "update-notes/v3.25.16", label: "3.25.16" },
						{ type: "doc", id: "update-notes/v3.25.15", label: "3.25.15" },
						{ type: "doc", id: "update-notes/v3.25.14", label: "3.25.14" },
						{ type: "doc", id: "update-notes/v3.25.13", label: "3.25.13" },
						{ type: "doc", id: "update-notes/v3.25.12", label: "3.25.12" },
						{ type: "doc", id: "update-notes/v3.25.11", label: "3.25.11" },
						{ type: "doc", id: "update-notes/v3.25.10", label: "3.25.10" },
						{ type: "doc", id: "update-notes/v3.25.9", label: "3.25.9" },
						{ type: "doc", id: "update-notes/v3.25.8", label: "3.25.8" },
						{ type: "doc", id: "update-notes/v3.25.7", label: "3.25.7" },
						{ type: "doc", id: "update-notes/v3.25.6", label: "3.25.6" },
						{ type: "doc", id: "update-notes/v3.25.5", label: "3.25.5" },
						{ type: "doc", id: "update-notes/v3.25.4", label: "3.25.4" },
						{ type: "doc", id: "update-notes/v3.25.3", label: "3.25.3" },
						{ type: "doc", id: "update-notes/v3.25.2", label: "3.25.2" },
						{ type: "doc", id: "update-notes/v3.25.1", label: "3.25.1" },
						{ type: "doc", id: "update-notes/v3.25.0", label: "3.25.0" },
					],
				},
				{
					type: "category",
					label: "3.24",
					items: [{ type: "doc", id: "update-notes/v3.24.0", label: "3.24.0" }],
				},
				{
					type: "category",
					label: "3.23",
					items: [
						{ type: "doc", id: "update-notes/v3.23", label: "3.23 Combined" },
						{ type: "doc", id: "update-notes/v3.23.19", label: "3.23.19" },
						{ type: "doc", id: "update-notes/v3.23.18", label: "3.23.18" },
						{ type: "doc", id: "update-notes/v3.23.17", label: "3.23.17" },
						{ type: "doc", id: "update-notes/v3.23.16", label: "3.23.16" },
						{ type: "doc", id: "update-notes/v3.23.15", label: "3.23.15" },
						{ type: "doc", id: "update-notes/v3.23.14", label: "3.23.14" },
						{ type: "doc", id: "update-notes/v3.23.13", label: "3.23.13" },
						{ type: "doc", id: "update-notes/v3.23.12", label: "3.23.12" },
						{ type: "doc", id: "update-notes/v3.23.11", label: "3.23.11" },
						{ type: "doc", id: "update-notes/v3.23.10", label: "3.23.10" },
						{ type: "doc", id: "update-notes/v3.23.9", label: "3.23.9" },
						{ type: "doc", id: "update-notes/v3.23.8", label: "3.23.8" },
						{ type: "doc", id: "update-notes/v3.23.7", label: "3.23.7" },
						{ type: "doc", id: "update-notes/v3.23.6", label: "3.23.6" },
						{ type: "doc", id: "update-notes/v3.23.5", label: "3.23.5" },
						{ type: "doc", id: "update-notes/v3.23.4", label: "3.23.4" },
						{ type: "doc", id: "update-notes/v3.23.3", label: "3.23.3" },
						{ type: "doc", id: "update-notes/v3.23.2", label: "3.23.2" },
						{ type: "doc", id: "update-notes/v3.23.1", label: "3.23.1" },
						{ type: "doc", id: "update-notes/v3.23.0", label: "3.23.0" },
					],
				},
				{
					type: "category",
					label: "3.22",
					items: [
						{ type: "doc", id: "update-notes/v3.22.6", label: "3.22.6" },
						{ type: "doc", id: "update-notes/v3.22.5", label: "3.22.5" },
						{ type: "doc", id: "update-notes/v3.22.4", label: "3.22.4" },
						{ type: "doc", id: "update-notes/v3.22.3", label: "3.22.3" },
						{ type: "doc", id: "update-notes/v3.22.2", label: "3.22.2" },
						{ type: "doc", id: "update-notes/v3.22.1", label: "3.22.1" },
						{ type: "doc", id: "update-notes/v3.22", label: "3.22 Combined" },
						{ type: "doc", id: "update-notes/v3.22.0", label: "3.22.0" },
					],
				},
				{
					type: "category",
					label: "3.21",
					items: [
						{ type: "doc", id: "update-notes/v3.21", label: "3.21 Combined" },
						{ type: "doc", id: "update-notes/v3.21.5", label: "3.21.5" },
						{ type: "doc", id: "update-notes/v3.21.4", label: "3.21.4" },
						{ type: "doc", id: "update-notes/v3.21.3", label: "3.21.3" },
						{ type: "doc", id: "update-notes/v3.21.2", label: "3.21.2" },
						{ type: "doc", id: "update-notes/v3.21.1", label: "3.21.1" },
						{ type: "doc", id: "update-notes/v3.21.0", label: "3.21.0" },
					],
				},
				{
					type: "category",
					label: "3.20",
					items: [
						{ type: "doc", id: "update-notes/v3.20", label: "3.20 Combined" },
						{ type: "doc", id: "update-notes/v3.20.3", label: "3.20.3" },
						{ type: "doc", id: "update-notes/v3.20.2", label: "3.20.2" },
						{ type: "doc", id: "update-notes/v3.20.1", label: "3.20.1" },
						{ type: "doc", id: "update-notes/v3.20.0", label: "3.20.0" },
					],
				},
				{
					type: "category",
					label: "3.19",
					items: [
						{ type: "doc", id: "update-notes/v3.19", label: "3.19 Combined" },
						{ type: "doc", id: "update-notes/v3.19.0", label: "3.19.0" },
						{ type: "doc", id: "update-notes/v3.19.1", label: "3.19.1" },
						{ type: "doc", id: "update-notes/v3.19.2", label: "3.19.2" },
						{ type: "doc", id: "update-notes/v3.19.3", label: "3.19.3" },
						{ type: "doc", id: "update-notes/v3.19.4", label: "3.19.4" },
						{ type: "doc", id: "update-notes/v3.19.5", label: "3.19.5" },
						{ type: "doc", id: "update-notes/v3.19.6", label: "3.19.6" },
						{ type: "doc", id: "update-notes/v3.19.7", label: "3.19.7" },
					],
				},
				{
					type: "category",
					label: "3.18",
					items: [
						{ type: "doc", id: "update-notes/v3.18", label: "3.18 Combined" },
						{ type: "doc", id: "update-notes/v3.18.0", label: "3.18.0" },
						{ type: "doc", id: "update-notes/v3.18.1", label: "3.18.1" },
						{ type: "doc", id: "update-notes/v3.18.2", label: "3.18.2" },
						{ type: "doc", id: "update-notes/v3.18.3", label: "3.18.3" },
						{ type: "doc", id: "update-notes/v3.18.4", label: "3.18.4" },
						{ type: "doc", id: "update-notes/v3.18.5", label: "3.18.5" },
					],
				},
				{
					type: "category",
					label: "3.17",
					items: [
						{ type: "doc", id: "update-notes/v3.17", label: "3.17 Combined" },
						{ type: "doc", id: "update-notes/v3.17.0", label: "3.17.0" },
						{ type: "doc", id: "update-notes/v3.17.1", label: "3.17.1" },
						{ type: "doc", id: "update-notes/v3.17.2", label: "3.17.2" },
					],
				},
				{
					type: "category",
					label: "3.16",
					items: [
						{ type: "doc", id: "update-notes/v3.16", label: "3.16 Combined" },
						{ type: "doc", id: "update-notes/v3.16.0", label: "3.16.0" },
						{ type: "doc", id: "update-notes/v3.16.1", label: "3.16.1" },
						{ type: "doc", id: "update-notes/v3.16.2", label: "3.16.2" },
						{ type: "doc", id: "update-notes/v3.16.3", label: "3.16.3" },
						{ type: "doc", id: "update-notes/v3.16.4", label: "3.16.4" },
						{ type: "doc", id: "update-notes/v3.16.5", label: "3.16.5" },
						{ type: "doc", id: "update-notes/v3.16.6", label: "3.16.6" },
					],
				},
				{
					type: "category",
					label: "3.15",
					items: [
						{ type: "doc", id: "update-notes/v3.15", label: "3.15 Combined" },
						{ type: "doc", id: "update-notes/v3.15.0", label: "3.15.0" },
						{ type: "doc", id: "update-notes/v3.15.1", label: "3.15.1" },
						{ type: "doc", id: "update-notes/v3.15.2", label: "3.15.2" },
						{ type: "doc", id: "update-notes/v3.15.3", label: "3.15.3" },
						{ type: "doc", id: "update-notes/v3.15.4", label: "3.15.4" },
						{ type: "doc", id: "update-notes/v3.15.5", label: "3.15.5" },
					],
				},
				{
					type: "category",
					label: "3.14",
					items: [
						{ type: "doc", id: "update-notes/v3.14", label: "3.14 Combined" },
						{ type: "doc", id: "update-notes/v3.14.0", label: "3.14.0" },
						{ type: "doc", id: "update-notes/v3.14.1", label: "3.14.1" },
						{ type: "doc", id: "update-notes/v3.14.2", label: "3.14.2" },
						{ type: "doc", id: "update-notes/v3.14.3", label: "3.14.3" },
					],
				},
				{
					type: "category",
					label: "3.13",
					items: [
						{ type: "doc", id: "update-notes/v3.13", label: "3.13 Combined" },
						{ type: "doc", id: "update-notes/v3.13.0", label: "3.13.0" },
						{ type: "doc", id: "update-notes/v3.13.1", label: "3.13.1" },
						{ type: "doc", id: "update-notes/v3.13.2", label: "3.13.2" },
					],
				},
				{
					type: "category",
					label: "3.12",
					items: [
						{ type: "doc", id: "update-notes/v3.12", label: "3.12 Combined" },
						{ type: "doc", id: "update-notes/v3.12.0", label: "3.12.0" },
						{ type: "doc", id: "update-notes/v3.12.1", label: "3.12.1" },
						{ type: "doc", id: "update-notes/v3.12.2", label: "3.12.2" },
						{ type: "doc", id: "update-notes/v3.12.3", label: "3.12.3" },
					],
				},
				{
					type: "category",
					label: "3.11",
					items: [
						{ type: "doc", id: "update-notes/v3.11", label: "3.11 Combined" },
						{ type: "doc", id: "update-notes/v3.11.0", label: "3.11.0" },
						{ type: "doc", id: "update-notes/v3.11.1", label: "3.11.1" },
						{ type: "doc", id: "update-notes/v3.11.2", label: "3.11.2" },
						{ type: "doc", id: "update-notes/v3.11.3", label: "3.11.3" },
						{ type: "doc", id: "update-notes/v3.11.4", label: "3.11.4" },
						{ type: "doc", id: "update-notes/v3.11.5", label: "3.11.5" },
						{ type: "doc", id: "update-notes/v3.11.6", label: "3.11.6" },
						{ type: "doc", id: "update-notes/v3.11.7", label: "3.11.7" },
						{ type: "doc", id: "update-notes/v3.11.8", label: "3.11.8" },
						{ type: "doc", id: "update-notes/v3.11.9", label: "3.11.9" },
						{ type: "doc", id: "update-notes/v3.11.10", label: "3.11.10" },
						{ type: "doc", id: "update-notes/v3.11.11", label: "3.11.11" },
						{ type: "doc", id: "update-notes/v3.11.12", label: "3.11.12" },
						{ type: "doc", id: "update-notes/v3.11.13", label: "3.11.13" },
						{ type: "doc", id: "update-notes/v3.11.14", label: "3.11.14" },
						{ type: "doc", id: "update-notes/v3.11.15", label: "3.11.15" },
						{ type: "doc", id: "update-notes/v3.11.16", label: "3.11.16" },
						{ type: "doc", id: "update-notes/v3.11.17", label: "3.11.17" },
					],
				},
				{
					type: "category",
					label: "3.10",
					items: [
						{ type: "doc", id: "update-notes/v3.10", label: "3.10 Combined" },
						{ type: "doc", id: "update-notes/v3.10.0", label: "3.10.0" },
						{ type: "doc", id: "update-notes/v3.10.1", label: "3.10.1" },
						{ type: "doc", id: "update-notes/v3.10.2", label: "3.10.2" },
						{ type: "doc", id: "update-notes/v3.10.3", label: "3.10.3" },
						{ type: "doc", id: "update-notes/v3.10.4", label: "3.10.4" },
						{ type: "doc", id: "update-notes/v3.10.5", label: "3.10.5" },
					],
				},
				{
					type: "category",
					label: "3.9",
					items: [
						{ type: "doc", id: "update-notes/v3.9", label: "3.9 Combined" },
						{ type: "doc", id: "update-notes/v3.9.0", label: "3.9.0" },
						{ type: "doc", id: "update-notes/v3.9.1", label: "3.9.1" },
						{ type: "doc", id: "update-notes/v3.9.2", label: "3.9.2" },
					],
				},
				{
					type: "category",
					label: "3.8",
					items: [
						{ type: "doc", id: "update-notes/v3.8", label: "3.8 Combined" },
						{ type: "doc", id: "update-notes/v3.8.0", label: "3.8.0" },
						{ type: "doc", id: "update-notes/v3.8.1", label: "3.8.1" },
						{ type: "doc", id: "update-notes/v3.8.2", label: "3.8.2" },
						{ type: "doc", id: "update-notes/v3.8.3", label: "3.8.3" },
						{ type: "doc", id: "update-notes/v3.8.4", label: "3.8.4" },
						{ type: "doc", id: "update-notes/v3.8.5", label: "3.8.5" },
						{ type: "doc", id: "update-notes/v3.8.6", label: "3.8.6" },
					],
				},
				{
					type: "category",
					label: "3.7",
					items: [
						{ type: "doc", id: "update-notes/v3.7", label: "3.7 Combined" },
						{ type: "doc", id: "update-notes/v3.7.0", label: "3.7.0" },
						{ type: "doc", id: "update-notes/v3.7.1", label: "3.7.1" },
						{ type: "doc", id: "update-notes/v3.7.2", label: "3.7.2" },
						{ type: "doc", id: "update-notes/v3.7.3", label: "3.7.3" },
						{ type: "doc", id: "update-notes/v3.7.4", label: "3.7.4" },
						{ type: "doc", id: "update-notes/v3.7.5", label: "3.7.5" },
						{ type: "doc", id: "update-notes/v3.7.6", label: "3.7.6" },
						{ type: "doc", id: "update-notes/v3.7.7", label: "3.7.7" },
						{ type: "doc", id: "update-notes/v3.7.8", label: "3.7.8" },
						{ type: "doc", id: "update-notes/v3.7.9", label: "3.7.9" },
						{ type: "doc", id: "update-notes/v3.7.10", label: "3.7.10" },
						{ type: "doc", id: "update-notes/v3.7.11", label: "3.7.11" },
						{ type: "doc", id: "update-notes/v3.7.12", label: "3.7.12" },
					],
				},
				{
					type: "category",
					label: "3.3",
					items: [
						{ type: "doc", id: "update-notes/v3.3", label: "3.3 Combined" },
						{ type: "doc", id: "update-notes/v3.3.0", label: "3.3.0" },
						{ type: "doc", id: "update-notes/v3.3.1", label: "3.3.1" },
						{ type: "doc", id: "update-notes/v3.3.2", label: "3.3.2" },
						{ type: "doc", id: "update-notes/v3.3.3", label: "3.3.3" },
						{ type: "doc", id: "update-notes/v3.3.4", label: "3.3.4" },
						{ type: "doc", id: "update-notes/v3.3.5", label: "3.3.5" },
						{ type: "doc", id: "update-notes/v3.3.6", label: "3.3.6" },
						{ type: "doc", id: "update-notes/v3.3.7", label: "3.3.7" },
						{ type: "doc", id: "update-notes/v3.3.8", label: "3.3.8" },
						{ type: "doc", id: "update-notes/v3.3.9", label: "3.3.9" },
						{ type: "doc", id: "update-notes/v3.3.10", label: "3.3.10" },
						{ type: "doc", id: "update-notes/v3.3.11", label: "3.3.11" },
						{ type: "doc", id: "update-notes/v3.3.12", label: "3.3.12" },
						{ type: "doc", id: "update-notes/v3.3.13", label: "3.3.13" },
						{ type: "doc", id: "update-notes/v3.3.14", label: "3.3.14" },
						{ type: "doc", id: "update-notes/v3.3.15", label: "3.3.15" },
						{ type: "doc", id: "update-notes/v3.3.16", label: "3.3.16" },
						{ type: "doc", id: "update-notes/v3.3.17", label: "3.3.17" },
						{ type: "doc", id: "update-notes/v3.3.18", label: "3.3.18" },
						{ type: "doc", id: "update-notes/v3.3.19", label: "3.3.19" },
						{ type: "doc", id: "update-notes/v3.3.20", label: "3.3.20" },
						{ type: "doc", id: "update-notes/v3.3.21", label: "3.3.21" },
						{ type: "doc", id: "update-notes/v3.3.22", label: "3.3.22" },
						{ type: "doc", id: "update-notes/v3.3.23", label: "3.3.23" },
						{ type: "doc", id: "update-notes/v3.3.24", label: "3.3.24" },
						{ type: "doc", id: "update-notes/v3.3.25", label: "3.3.25" },
						{ type: "doc", id: "update-notes/v3.3.26", label: "3.3.26" },
					],
				},
				{
					type: "category",
					label: "3.1",
					items: [
						{ type: "doc", id: "update-notes/v3.1", label: "3.1 Combined" },
						{ type: "doc", id: "update-notes/v3.1.0", label: "3.1.0" },
						{ type: "doc", id: "update-notes/v3.1.1", label: "3.1.1" },
						{ type: "doc", id: "update-notes/v3.1.2", label: "3.1.2" },
						{ type: "doc", id: "update-notes/v3.1.3", label: "3.1.3" },
						{ type: "doc", id: "update-notes/v3.1.4", label: "3.1.4" }, // Includes 3.1.5 fix
						{ type: "doc", id: "update-notes/v3.1.6", label: "3.1.6" },
						{ type: "doc", id: "update-notes/v3.1.7", label: "3.1.7" },
					],
				},
				{
					type: "category",
					label: "3.0",
					items: [
						{ type: "doc", id: "update-notes/v3.0", label: "3.0 Combined" },
						{ type: "doc", id: "update-notes/v3.0.0", label: "3.0.0" },
						{ type: "doc", id: "update-notes/v3.0.1", label: "3.0.1" },
						{ type: "doc", id: "update-notes/v3.0.2", label: "3.0.2" },
						{ type: "doc", id: "update-notes/v3.0.3", label: "3.0.3" },
					],
				},
				{
					type: "category",
					label: "3.2",
					items: [
						{ type: "doc", id: "update-notes/v3.2", label: "3.2 Combined" },
						{ type: "doc", id: "update-notes/v3.2.0", label: "3.2.0" }, // Includes 3.2.1, 3.2.2
						{ type: "doc", id: "update-notes/v3.2.3", label: "3.2.3" },
						{ type: "doc", id: "update-notes/v3.2.4", label: "3.2.4" },
						{ type: "doc", id: "update-notes/v3.2.5", label: "3.2.5" },
						{ type: "doc", id: "update-notes/v3.2.6", label: "3.2.6" },
						{ type: "doc", id: "update-notes/v3.2.7", label: "3.2.7" },
						{ type: "doc", id: "update-notes/v3.2.8", label: "3.2.8" },
					],
				},
				{
					type: "category",
					label: "2.2",
					items: [
						{ type: "doc", id: "update-notes/v2.2", label: "2.2 Combined" },
						{ type: "doc", id: "update-notes/v2.2.0", label: "2.2.0" },
						{ type: "doc", id: "update-notes/v2.2.1", label: "2.2.1" },
						{ type: "doc", id: "update-notes/v2.2.2", label: "2.2.2" },
						{ type: "doc", id: "update-notes/v2.2.3", label: "2.2.3" },
						{ type: "doc", id: "update-notes/v2.2.4", label: "2.2.4" },
						{ type: "doc", id: "update-notes/v2.2.5", label: "2.2.5" },
						{ type: "doc", id: "update-notes/v2.2.6", label: "2.2.6" }, // Includes 2.2.7-2.2.10
						{ type: "doc", id: "update-notes/v2.2.11", label: "2.2.11" },
						{ type: "doc", id: "update-notes/v2.2.12", label: "2.2.12" },
						{ type: "doc", id: "update-notes/v2.2.13", label: "2.2.13" },
						{ type: "doc", id: "update-notes/v2.2.14", label: "2.2.14" }, // Includes 2.2.15
						{ type: "doc", id: "update-notes/v2.2.16", label: "2.2.16" },
						{ type: "doc", id: "update-notes/v2.2.17", label: "2.2.17" },
						{ type: "doc", id: "update-notes/v2.2.18", label: "2.2.18" },
						{ type: "doc", id: "update-notes/v2.2.19", label: "2.2.19" },
						{ type: "doc", id: "update-notes/v2.2.20", label: "2.2.20" },
						{ type: "doc", id: "update-notes/v2.2.21", label: "2.2.21" },
						{ type: "doc", id: "update-notes/v2.2.22", label: "2.2.22" },
						{ type: "doc", id: "update-notes/v2.2.23", label: "2.2.23" },
						{ type: "doc", id: "update-notes/v2.2.24", label: "2.2.24" },
						{ type: "doc", id: "update-notes/v2.2.25", label: "2.2.25" },
						{ type: "doc", id: "update-notes/v2.2.26", label: "2.2.26" },
						{ type: "doc", id: "update-notes/v2.2.27", label: "2.2.27" },
						{ type: "doc", id: "update-notes/v2.2.28", label: "2.2.28" },
						{ type: "doc", id: "update-notes/v2.2.29", label: "2.2.29" },
						{ type: "doc", id: "update-notes/v2.2.30", label: "2.2.30" },
						{ type: "doc", id: "update-notes/v2.2.31", label: "2.2.31" },
						{ type: "doc", id: "update-notes/v2.2.32", label: "2.2.32" },
						{ type: "doc", id: "update-notes/v2.2.33", label: "2.2.33" },
						{ type: "doc", id: "update-notes/v2.2.34", label: "2.2.34" },
						{ type: "doc", id: "update-notes/v2.2.35", label: "2.2.35" },
						{ type: "doc", id: "update-notes/v2.2.36", label: "2.2.36" }, // Includes 2.2.37
						{ type: "doc", id: "update-notes/v2.2.38", label: "2.2.38" },
						{ type: "doc", id: "update-notes/v2.2.39", label: "2.2.39" },
						{ type: "doc", id: "update-notes/v2.2.40", label: "2.2.40" },
						{ type: "doc", id: "update-notes/v2.2.41", label: "2.2.41" },
						{ type: "doc", id: "update-notes/v2.2.42", label: "2.2.42" },
						{ type: "doc", id: "update-notes/v2.2.43", label: "2.2.43" },
						{ type: "doc", id: "update-notes/v2.2.44", label: "2.2.44" },
						{ type: "doc", id: "update-notes/v2.2.45", label: "2.2.45" },
						{ type: "doc", id: "update-notes/v2.2.46", label: "2.2.46" },
					],
				},
				{
					type: "category",
					label: "2.1",
					items: [
						{ type: "doc", id: "update-notes/v2.1", label: "2.1 Combined" },
						{ type: "doc", id: "update-notes/v2.1.2", label: "2.1.2" },
						{ type: "doc", id: "update-notes/v2.1.3", label: "2.1.3" },
						{ type: "doc", id: "update-notes/v2.1.4", label: "2.1.4" },
						{ type: "doc", id: "update-notes/v2.1.5", label: "2.1.5" },
						{ type: "doc", id: "update-notes/v2.1.6", label: "2.1.6" },
						{ type: "doc", id: "update-notes/v2.1.7", label: "2.1.7" },
						{ type: "doc", id: "update-notes/v2.1.8", label: "2.1.8" },
						{ type: "doc", id: "update-notes/v2.1.9", label: "2.1.9" },
						{ type: "doc", id: "update-notes/v2.1.10", label: "2.1.10" },
						{ type: "doc", id: "update-notes/v2.1.11", label: "2.1.11" },
						{ type: "doc", id: "update-notes/v2.1.12", label: "2.1.12" },
						{ type: "doc", id: "update-notes/v2.1.13", label: "2.1.13" },
						{ type: "doc", id: "update-notes/v2.1.14", label: "2.1.14" },
						{ type: "doc", id: "update-notes/v2.1.15", label: "2.1.15" },
						{ type: "doc", id: "update-notes/v2.1.16", label: "2.1.16" },
						{ type: "doc", id: "update-notes/v2.1.17", label: "2.1.17" },
						{ type: "doc", id: "update-notes/v2.1.18", label: "2.1.18" },
						{ type: "doc", id: "update-notes/v2.1.19", label: "2.1.19" },
						{ type: "doc", id: "update-notes/v2.1.20", label: "2.1.20" },
						{ type: "doc", id: "update-notes/v2.1.21", label: "2.1.21" },
					],
				},
			],
		},
		{
			type: "doc",
			label: "FAQ",
			id: "faq",
		},
		{
			type: "link",
			label: "Roocabulary (GitHub)",
			href: "https://github.com/cannuri/Roocabulary",
		},
	],
}

export default sidebars
