export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/RooCodeInc/Roo-Code",
	GITHUB_DISCUSSIONS: "https://github.com/RooCodeInc/Roo-Code/discussions",
	X: "https://x.com/roocode",
	LINKEDIN: "https://www.linkedin.com/company/roo-code",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/roocode.bsky.social",
	DOCUMENTATION: "https://roocodeinc.github.io/Roo-Code/",
	SLACK_DOCS: "https://roocodeinc.github.io/Roo-Code/roo-code-cloud/slack-integration",
	CAREERS: "https://careers.roocode.com",
	ISSUES: "https://github.com/RooCodeInc/Roo-Code/issues",
	CHANGELOG: "https://github.com/RooCodeInc/Roo-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/RooCodeInc/Roo-Code/blob/main/PRIVACY.md",
	TUTORIALS: "https://roocodeinc.github.io/Roo-Code/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline",
	SECURITY: "https://trust.roocode.com",
	BLOG_SUBSTACK: "https://blog.roocode.com",
	FAQ: "https://roocode.com/#faq",
	TESTIMONIALS: "https://roocode.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.roocode.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.roocode.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.roocode.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.roocode.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.roocode.com/checkout/team",
	SUPPORT: "mailto:support@roocode.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
